#
# Раздел, где описываются контейнеры/сервисы, которые будут подняты через Docker Compose.
#
services:
  # Имя сервиса в рамках этого compose-файла.
  # Это “логическое” название, по которому Docker Compose понимает, что запускать.
  postgres:
    # Базовый образ Docker с PostgreSQL версии 16.
    # При первом запуске Docker скачает этот образ, а дальше будет использовать локальный.
    image: postgres:16

    # Явное имя контейнера в Docker.
    # Без этого имя обычно генерируется с префиксами, зависящими от папки проекта.
    container_name: mini-media-postgres

    # Блок переменных окружения, которые будут переданы в контейнер.
    # Построены под формат, который ожидает официальный образ PostgreSQL.
    environment:
      # Имя базы данных, которую официальный образ создаст при первой инициализации кластера.
      POSTGRES_DB: mini_media

      # Имя пользователя PostgreSQL, который будет создан при первой инициализации.
      POSTGRES_USER: mini_media

      # Пароль для пользователя POSTGRES_USER.
      POSTGRES_PASSWORD: mini_media_pass

    # Проброс портов с контейнера на хост.
    # Нужно, чтобы ваша Nest-приложение на Windows могло подключаться к Postgres через localhost.
    ports:
      # Формат: "hostPort:containerPort".
      # Здесь 5432 на хосте пробрасывается в 5432 внутри контейнера.
      - "5432:5432"

    # Блок volume-маунтов (куда и что монтируется).
    volumes:
      # Именованный volume.
      # Лежит “где-то” на хосте Docker, но нам не важно где именно.
      # Главное: данные Postgres сохраняются между перезапусками контейнера.
      - mini_media_pgdata:/var/lib/postgresql/data

    # Политика перезапуска контейнера.
    # "unless-stopped" означает: перезапуск при падении/рестарте Docker будет,
    # но если вы остановите контейнер руками, он не поднимется снова автоматически.
    restart: unless-stopped

    # Healthcheck — периодическая проверка “живости” сервиса.
    # Docker Compose будет считать контейнер здоровым/нездоровым по результату проверки.
    healthcheck:
      # Команда проверки:
      # pg_isready смотрит, готов ли сервер принимать подключения.
      test: ["CMD-SHELL", "pg_isready -U mini_media -d mini_media"]

      # Интервал между проверками healthcheck.
      interval: 5s

      # Максимальное время ожидания одной проверки.
      timeout: 3s

      # Сколько подряд неудачных проверок нужно, чтобы пометить сервис как unhealthy.
      retries: 20

# Раздел, в котором описываются именованные volume-ресурсы, используемые выше.
volumes:
  # Создание именованного volume.
  # Это обеспечивает персистентность данных Postgres между запусками.
  mini_media_pgdata:

# wsl-пароль: 4815162342